// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// StandardRenderingPipeline represents a babylon.js StandardRenderingPipeline.
// Standard rendering pipeline
// Default pipeline should be used going forward but the standard pipeline will be kept for backwards compatibility.
//
// See: https://doc.babylonjs.com/how_to/using_standard_rendering_pipeline
type StandardRenderingPipeline struct {
	*PostProcessRenderPipeline
	ctx js.Value
}

// JSObject returns the underlying js.Value.
func (s *StandardRenderingPipeline) JSObject() js.Value { return s.p }

// StandardRenderingPipeline returns a StandardRenderingPipeline JavaScript class.
func (ba *Babylon) StandardRenderingPipeline() *StandardRenderingPipeline {
	p := ba.ctx.Get("StandardRenderingPipeline")
	return StandardRenderingPipelineFromJSObject(p, ba.ctx)
}

// StandardRenderingPipelineFromJSObject returns a wrapped StandardRenderingPipeline JavaScript class.
func StandardRenderingPipelineFromJSObject(p js.Value, ctx js.Value) *StandardRenderingPipeline {
	return &StandardRenderingPipeline{PostProcessRenderPipeline: PostProcessRenderPipelineFromJSObject(p, ctx), ctx: ctx}
}

// StandardRenderingPipelineArrayToJSArray returns a JavaScript Array for the wrapped array.
func StandardRenderingPipelineArrayToJSArray(array []*StandardRenderingPipeline) []interface{} {
	var result []interface{}
	for _, v := range array {
		result = append(result, v.JSObject())
	}
	return result
}

// NewStandardRenderingPipelineOpts contains optional parameters for NewStandardRenderingPipeline.
type NewStandardRenderingPipelineOpts struct {
	OriginalPostProcess *PostProcess
	Cameras             []*Camera
}

// NewStandardRenderingPipeline returns a new StandardRenderingPipeline object.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#constructor
func (ba *Babylon) NewStandardRenderingPipeline(name string, scene *Scene, ratio float64, opts *NewStandardRenderingPipelineOpts) *StandardRenderingPipeline {
	if opts == nil {
		opts = &NewStandardRenderingPipelineOpts{}
	}

	args := make([]interface{}, 0, 3+2)

	args = append(args, name)
	args = append(args, scene.JSObject())
	args = append(args, ratio)

	if opts.OriginalPostProcess == nil {
		args = append(args, js.Undefined())
	} else {
		args = append(args, opts.OriginalPostProcess.JSObject())
	}
	if opts.Cameras == nil {
		args = append(args, js.Undefined())
	} else {
		args = append(args, CameraArrayToJSArray(opts.Cameras))
	}

	p := ba.ctx.Get("StandardRenderingPipeline").New(args...)
	return StandardRenderingPipelineFromJSObject(p, ba.ctx)
}

// Dispose calls the Dispose method on the StandardRenderingPipeline object.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#dispose
func (s *StandardRenderingPipeline) Dispose() {

	s.p.Call("dispose")
}

// Parse calls the Parse method on the StandardRenderingPipeline object.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#parse
func (s *StandardRenderingPipeline) Parse(source JSObject, scene *Scene, rootUrl string) *StandardRenderingPipeline {

	args := make([]interface{}, 0, 3+0)

	if source == nil {
		args = append(args, js.Null())
	} else {
		args = append(args, source.JSObject())
	}

	if scene == nil {
		args = append(args, js.Null())
	} else {
		args = append(args, scene.JSObject())
	}

	args = append(args, rootUrl)

	retVal := s.p.Call("Parse", args...)
	return StandardRenderingPipelineFromJSObject(retVal, s.ctx)
}

// Serialize calls the Serialize method on the StandardRenderingPipeline object.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#serialize
func (s *StandardRenderingPipeline) Serialize() js.Value {

	retVal := s.p.Call("serialize")
	return retVal
}

// Animations returns the Animations property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#animations
func (s *StandardRenderingPipeline) Animations() []*Animation {
	retVal := s.p.Get("animations")
	result := []*Animation{}
	for ri := 0; ri < retVal.Length(); ri++ {
		result = append(result, AnimationFromJSObject(retVal.Index(ri), s.ctx))
	}
	return result
}

// SetAnimations sets the Animations property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#animations
func (s *StandardRenderingPipeline) SetAnimations(animations []*Animation) *StandardRenderingPipeline {
	s.p.Set("animations", animations)
	return s
}

// BlurHPostProcesses returns the BlurHPostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurhpostprocesses
func (s *StandardRenderingPipeline) BlurHPostProcesses() []*PostProcess {
	retVal := s.p.Get("blurHPostProcesses")
	result := []*PostProcess{}
	for ri := 0; ri < retVal.Length(); ri++ {
		result = append(result, PostProcessFromJSObject(retVal.Index(ri), s.ctx))
	}
	return result
}

// SetBlurHPostProcesses sets the BlurHPostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurhpostprocesses
func (s *StandardRenderingPipeline) SetBlurHPostProcesses(blurHPostProcesses []*PostProcess) *StandardRenderingPipeline {
	s.p.Set("blurHPostProcesses", blurHPostProcesses)
	return s
}

// BlurVPostProcesses returns the BlurVPostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurvpostprocesses
func (s *StandardRenderingPipeline) BlurVPostProcesses() []*PostProcess {
	retVal := s.p.Get("blurVPostProcesses")
	result := []*PostProcess{}
	for ri := 0; ri < retVal.Length(); ri++ {
		result = append(result, PostProcessFromJSObject(retVal.Index(ri), s.ctx))
	}
	return result
}

// SetBlurVPostProcesses sets the BlurVPostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurvpostprocesses
func (s *StandardRenderingPipeline) SetBlurVPostProcesses(blurVPostProcesses []*PostProcess) *StandardRenderingPipeline {
	s.p.Set("blurVPostProcesses", blurVPostProcesses)
	return s
}

// BlurWidth returns the BlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurwidth
func (s *StandardRenderingPipeline) BlurWidth() float64 {
	retVal := s.p.Get("blurWidth")
	return retVal.Float()
}

// SetBlurWidth sets the BlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#blurwidth
func (s *StandardRenderingPipeline) SetBlurWidth(blurWidth float64) *StandardRenderingPipeline {
	s.p.Set("blurWidth", blurWidth)
	return s
}

// BrightPassPostProcess returns the BrightPassPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#brightpasspostprocess
func (s *StandardRenderingPipeline) BrightPassPostProcess() *PostProcess {
	retVal := s.p.Get("brightPassPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetBrightPassPostProcess sets the BrightPassPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#brightpasspostprocess
func (s *StandardRenderingPipeline) SetBrightPassPostProcess(brightPassPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("brightPassPostProcess", brightPassPostProcess.JSObject())
	return s
}

// BrightThreshold returns the BrightThreshold property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#brightthreshold
func (s *StandardRenderingPipeline) BrightThreshold() float64 {
	retVal := s.p.Get("brightThreshold")
	return retVal.Float()
}

// SetBrightThreshold sets the BrightThreshold property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#brightthreshold
func (s *StandardRenderingPipeline) SetBrightThreshold(brightThreshold float64) *StandardRenderingPipeline {
	s.p.Set("brightThreshold", brightThreshold)
	return s
}

// DepthOfFieldBlurWidth returns the DepthOfFieldBlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffieldblurwidth
func (s *StandardRenderingPipeline) DepthOfFieldBlurWidth() float64 {
	retVal := s.p.Get("depthOfFieldBlurWidth")
	return retVal.Float()
}

// SetDepthOfFieldBlurWidth sets the DepthOfFieldBlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffieldblurwidth
func (s *StandardRenderingPipeline) SetDepthOfFieldBlurWidth(depthOfFieldBlurWidth float64) *StandardRenderingPipeline {
	s.p.Set("depthOfFieldBlurWidth", depthOfFieldBlurWidth)
	return s
}

// DepthOfFieldDistance returns the DepthOfFieldDistance property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffielddistance
func (s *StandardRenderingPipeline) DepthOfFieldDistance() float64 {
	retVal := s.p.Get("depthOfFieldDistance")
	return retVal.Float()
}

// SetDepthOfFieldDistance sets the DepthOfFieldDistance property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffielddistance
func (s *StandardRenderingPipeline) SetDepthOfFieldDistance(depthOfFieldDistance float64) *StandardRenderingPipeline {
	s.p.Set("depthOfFieldDistance", depthOfFieldDistance)
	return s
}

// DepthOfFieldPostProcess returns the DepthOfFieldPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffieldpostprocess
func (s *StandardRenderingPipeline) DepthOfFieldPostProcess() *PostProcess {
	retVal := s.p.Get("depthOfFieldPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetDepthOfFieldPostProcess sets the DepthOfFieldPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#depthoffieldpostprocess
func (s *StandardRenderingPipeline) SetDepthOfFieldPostProcess(depthOfFieldPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("depthOfFieldPostProcess", depthOfFieldPostProcess.JSObject())
	return s
}

// DownSampleX4PostProcess returns the DownSampleX4PostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#downsamplex4postprocess
func (s *StandardRenderingPipeline) DownSampleX4PostProcess() *PostProcess {
	retVal := s.p.Get("downSampleX4PostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetDownSampleX4PostProcess sets the DownSampleX4PostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#downsamplex4postprocess
func (s *StandardRenderingPipeline) SetDownSampleX4PostProcess(downSampleX4PostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("downSampleX4PostProcess", downSampleX4PostProcess.JSObject())
	return s
}

// Exposure returns the Exposure property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#exposure
func (s *StandardRenderingPipeline) Exposure() float64 {
	retVal := s.p.Get("exposure")
	return retVal.Float()
}

// SetExposure sets the Exposure property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#exposure
func (s *StandardRenderingPipeline) SetExposure(exposure float64) *StandardRenderingPipeline {
	s.p.Set("exposure", exposure)
	return s
}

// FxaaEnabled returns the FxaaEnabled property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#fxaaenabled
func (s *StandardRenderingPipeline) FxaaEnabled() bool {
	retVal := s.p.Get("fxaaEnabled")
	return retVal.Bool()
}

// SetFxaaEnabled sets the FxaaEnabled property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#fxaaenabled
func (s *StandardRenderingPipeline) SetFxaaEnabled(fxaaEnabled bool) *StandardRenderingPipeline {
	s.p.Set("fxaaEnabled", fxaaEnabled)
	return s
}

// FxaaPostProcess returns the FxaaPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#fxaapostprocess
func (s *StandardRenderingPipeline) FxaaPostProcess() *FxaaPostProcess {
	retVal := s.p.Get("fxaaPostProcess")
	return FxaaPostProcessFromJSObject(retVal, s.ctx)
}

// SetFxaaPostProcess sets the FxaaPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#fxaapostprocess
func (s *StandardRenderingPipeline) SetFxaaPostProcess(fxaaPostProcess *FxaaPostProcess) *StandardRenderingPipeline {
	s.p.Set("fxaaPostProcess", fxaaPostProcess.JSObject())
	return s
}

// HdrAutoExposure returns the HdrAutoExposure property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrautoexposure
func (s *StandardRenderingPipeline) HdrAutoExposure() bool {
	retVal := s.p.Get("hdrAutoExposure")
	return retVal.Bool()
}

// SetHdrAutoExposure sets the HdrAutoExposure property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrautoexposure
func (s *StandardRenderingPipeline) SetHdrAutoExposure(hdrAutoExposure bool) *StandardRenderingPipeline {
	s.p.Set("hdrAutoExposure", hdrAutoExposure)
	return s
}

// HdrDecreaseRate returns the HdrDecreaseRate property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrdecreaserate
func (s *StandardRenderingPipeline) HdrDecreaseRate() float64 {
	retVal := s.p.Get("hdrDecreaseRate")
	return retVal.Float()
}

// SetHdrDecreaseRate sets the HdrDecreaseRate property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrdecreaserate
func (s *StandardRenderingPipeline) SetHdrDecreaseRate(hdrDecreaseRate float64) *StandardRenderingPipeline {
	s.p.Set("hdrDecreaseRate", hdrDecreaseRate)
	return s
}

// HdrFinalPostProcess returns the HdrFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrfinalpostprocess
func (s *StandardRenderingPipeline) HdrFinalPostProcess() *PostProcess {
	retVal := s.p.Get("hdrFinalPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetHdrFinalPostProcess sets the HdrFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrfinalpostprocess
func (s *StandardRenderingPipeline) SetHdrFinalPostProcess(hdrFinalPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("hdrFinalPostProcess", hdrFinalPostProcess.JSObject())
	return s
}

// HdrIncreaseRate returns the HdrIncreaseRate property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrincreaserate
func (s *StandardRenderingPipeline) HdrIncreaseRate() float64 {
	retVal := s.p.Get("hdrIncreaseRate")
	return retVal.Float()
}

// SetHdrIncreaseRate sets the HdrIncreaseRate property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrincreaserate
func (s *StandardRenderingPipeline) SetHdrIncreaseRate(hdrIncreaseRate float64) *StandardRenderingPipeline {
	s.p.Set("hdrIncreaseRate", hdrIncreaseRate)
	return s
}

// HdrMinimumLuminance returns the HdrMinimumLuminance property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrminimumluminance
func (s *StandardRenderingPipeline) HdrMinimumLuminance() float64 {
	retVal := s.p.Get("hdrMinimumLuminance")
	return retVal.Float()
}

// SetHdrMinimumLuminance sets the HdrMinimumLuminance property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrminimumluminance
func (s *StandardRenderingPipeline) SetHdrMinimumLuminance(hdrMinimumLuminance float64) *StandardRenderingPipeline {
	s.p.Set("hdrMinimumLuminance", hdrMinimumLuminance)
	return s
}

// HdrPostProcess returns the HdrPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrpostprocess
func (s *StandardRenderingPipeline) HdrPostProcess() *PostProcess {
	retVal := s.p.Get("hdrPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetHdrPostProcess sets the HdrPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#hdrpostprocess
func (s *StandardRenderingPipeline) SetHdrPostProcess(hdrPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("hdrPostProcess", hdrPostProcess.JSObject())
	return s
}

// HorizontalBlur returns the HorizontalBlur property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#horizontalblur
func (s *StandardRenderingPipeline) HorizontalBlur() bool {
	retVal := s.p.Get("horizontalBlur")
	return retVal.Bool()
}

// SetHorizontalBlur sets the HorizontalBlur property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#horizontalblur
func (s *StandardRenderingPipeline) SetHorizontalBlur(horizontalBlur bool) *StandardRenderingPipeline {
	s.p.Set("horizontalBlur", horizontalBlur)
	return s
}

// LensColorTexture returns the LensColorTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lenscolortexture
func (s *StandardRenderingPipeline) LensColorTexture() *Texture {
	retVal := s.p.Get("lensColorTexture")
	return TextureFromJSObject(retVal, s.ctx)
}

// SetLensColorTexture sets the LensColorTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lenscolortexture
func (s *StandardRenderingPipeline) SetLensColorTexture(lensColorTexture *Texture) *StandardRenderingPipeline {
	s.p.Set("lensColorTexture", lensColorTexture.JSObject())
	return s
}

// LensFlareBlurWidth returns the LensFlareBlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflareblurwidth
func (s *StandardRenderingPipeline) LensFlareBlurWidth() float64 {
	retVal := s.p.Get("lensFlareBlurWidth")
	return retVal.Float()
}

// SetLensFlareBlurWidth sets the LensFlareBlurWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflareblurwidth
func (s *StandardRenderingPipeline) SetLensFlareBlurWidth(lensFlareBlurWidth float64) *StandardRenderingPipeline {
	s.p.Set("lensFlareBlurWidth", lensFlareBlurWidth)
	return s
}

// LensFlareComposePostProcess returns the LensFlareComposePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarecomposepostprocess
func (s *StandardRenderingPipeline) LensFlareComposePostProcess() *PostProcess {
	retVal := s.p.Get("lensFlareComposePostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetLensFlareComposePostProcess sets the LensFlareComposePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarecomposepostprocess
func (s *StandardRenderingPipeline) SetLensFlareComposePostProcess(lensFlareComposePostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("lensFlareComposePostProcess", lensFlareComposePostProcess.JSObject())
	return s
}

// LensFlareDirtTexture returns the LensFlareDirtTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflaredirttexture
func (s *StandardRenderingPipeline) LensFlareDirtTexture() *Texture {
	retVal := s.p.Get("lensFlareDirtTexture")
	return TextureFromJSObject(retVal, s.ctx)
}

// SetLensFlareDirtTexture sets the LensFlareDirtTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflaredirttexture
func (s *StandardRenderingPipeline) SetLensFlareDirtTexture(lensFlareDirtTexture *Texture) *StandardRenderingPipeline {
	s.p.Set("lensFlareDirtTexture", lensFlareDirtTexture.JSObject())
	return s
}

// LensFlareDistortionStrength returns the LensFlareDistortionStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflaredistortionstrength
func (s *StandardRenderingPipeline) LensFlareDistortionStrength() float64 {
	retVal := s.p.Get("lensFlareDistortionStrength")
	return retVal.Float()
}

// SetLensFlareDistortionStrength sets the LensFlareDistortionStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflaredistortionstrength
func (s *StandardRenderingPipeline) SetLensFlareDistortionStrength(lensFlareDistortionStrength float64) *StandardRenderingPipeline {
	s.p.Set("lensFlareDistortionStrength", lensFlareDistortionStrength)
	return s
}

// LensFlareFinalPostProcess returns the LensFlareFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarefinalpostprocess
func (s *StandardRenderingPipeline) LensFlareFinalPostProcess() *PostProcess {
	retVal := s.p.Get("lensFlareFinalPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetLensFlareFinalPostProcess sets the LensFlareFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarefinalpostprocess
func (s *StandardRenderingPipeline) SetLensFlareFinalPostProcess(lensFlareFinalPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("lensFlareFinalPostProcess", lensFlareFinalPostProcess.JSObject())
	return s
}

// LensFlareGhostDispersal returns the LensFlareGhostDispersal property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflareghostdispersal
func (s *StandardRenderingPipeline) LensFlareGhostDispersal() float64 {
	retVal := s.p.Get("lensFlareGhostDispersal")
	return retVal.Float()
}

// SetLensFlareGhostDispersal sets the LensFlareGhostDispersal property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflareghostdispersal
func (s *StandardRenderingPipeline) SetLensFlareGhostDispersal(lensFlareGhostDispersal float64) *StandardRenderingPipeline {
	s.p.Set("lensFlareGhostDispersal", lensFlareGhostDispersal)
	return s
}

// LensFlareHaloWidth returns the LensFlareHaloWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarehalowidth
func (s *StandardRenderingPipeline) LensFlareHaloWidth() float64 {
	retVal := s.p.Get("lensFlareHaloWidth")
	return retVal.Float()
}

// SetLensFlareHaloWidth sets the LensFlareHaloWidth property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarehalowidth
func (s *StandardRenderingPipeline) SetLensFlareHaloWidth(lensFlareHaloWidth float64) *StandardRenderingPipeline {
	s.p.Set("lensFlareHaloWidth", lensFlareHaloWidth)
	return s
}

// LensFlarePostProcess returns the LensFlarePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarepostprocess
func (s *StandardRenderingPipeline) LensFlarePostProcess() *PostProcess {
	retVal := s.p.Get("lensFlarePostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetLensFlarePostProcess sets the LensFlarePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarepostprocess
func (s *StandardRenderingPipeline) SetLensFlarePostProcess(lensFlarePostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("lensFlarePostProcess", lensFlarePostProcess.JSObject())
	return s
}

// LensFlareStrength returns the LensFlareStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarestrength
func (s *StandardRenderingPipeline) LensFlareStrength() float64 {
	retVal := s.p.Get("lensFlareStrength")
	return retVal.Float()
}

// SetLensFlareStrength sets the LensFlareStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensflarestrength
func (s *StandardRenderingPipeline) SetLensFlareStrength(lensFlareStrength float64) *StandardRenderingPipeline {
	s.p.Set("lensFlareStrength", lensFlareStrength)
	return s
}

// LensStarTexture returns the LensStarTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensstartexture
func (s *StandardRenderingPipeline) LensStarTexture() *Texture {
	retVal := s.p.Get("lensStarTexture")
	return TextureFromJSObject(retVal, s.ctx)
}

// SetLensStarTexture sets the LensStarTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lensstartexture
func (s *StandardRenderingPipeline) SetLensStarTexture(lensStarTexture *Texture) *StandardRenderingPipeline {
	s.p.Set("lensStarTexture", lensStarTexture.JSObject())
	return s
}

// LensTexture returns the LensTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lenstexture
func (s *StandardRenderingPipeline) LensTexture() *Texture {
	retVal := s.p.Get("lensTexture")
	return TextureFromJSObject(retVal, s.ctx)
}

// SetLensTexture sets the LensTexture property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#lenstexture
func (s *StandardRenderingPipeline) SetLensTexture(lensTexture *Texture) *StandardRenderingPipeline {
	s.p.Set("lensTexture", lensTexture.JSObject())
	return s
}

// LuminanceDownSamplePostProcesses returns the LuminanceDownSamplePostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancedownsamplepostprocesses
func (s *StandardRenderingPipeline) LuminanceDownSamplePostProcesses() []*PostProcess {
	retVal := s.p.Get("luminanceDownSamplePostProcesses")
	result := []*PostProcess{}
	for ri := 0; ri < retVal.Length(); ri++ {
		result = append(result, PostProcessFromJSObject(retVal.Index(ri), s.ctx))
	}
	return result
}

// SetLuminanceDownSamplePostProcesses sets the LuminanceDownSamplePostProcesses property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancedownsamplepostprocesses
func (s *StandardRenderingPipeline) SetLuminanceDownSamplePostProcesses(luminanceDownSamplePostProcesses []*PostProcess) *StandardRenderingPipeline {
	s.p.Set("luminanceDownSamplePostProcesses", luminanceDownSamplePostProcesses)
	return s
}

// LuminancePostProcess returns the LuminancePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancepostprocess
func (s *StandardRenderingPipeline) LuminancePostProcess() *PostProcess {
	retVal := s.p.Get("luminancePostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetLuminancePostProcess sets the LuminancePostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancepostprocess
func (s *StandardRenderingPipeline) SetLuminancePostProcess(luminancePostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("luminancePostProcess", luminancePostProcess.JSObject())
	return s
}

// LuminanceSteps returns the LuminanceSteps property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancesteps
func (s *StandardRenderingPipeline) LuminanceSteps() float64 {
	retVal := s.p.Get("LuminanceSteps")
	return retVal.Float()
}

// SetLuminanceSteps sets the LuminanceSteps property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#luminancesteps
func (s *StandardRenderingPipeline) SetLuminanceSteps(LuminanceSteps float64) *StandardRenderingPipeline {
	s.p.Set("LuminanceSteps", LuminanceSteps)
	return s
}

// MotionBlurPostProcess returns the MotionBlurPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionblurpostprocess
func (s *StandardRenderingPipeline) MotionBlurPostProcess() *PostProcess {
	retVal := s.p.Get("motionBlurPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetMotionBlurPostProcess sets the MotionBlurPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionblurpostprocess
func (s *StandardRenderingPipeline) SetMotionBlurPostProcess(motionBlurPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("motionBlurPostProcess", motionBlurPostProcess.JSObject())
	return s
}

// MotionBlurSamples returns the MotionBlurSamples property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionblursamples
func (s *StandardRenderingPipeline) MotionBlurSamples() float64 {
	retVal := s.p.Get("motionBlurSamples")
	return retVal.Float()
}

// SetMotionBlurSamples sets the MotionBlurSamples property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionblursamples
func (s *StandardRenderingPipeline) SetMotionBlurSamples(motionBlurSamples float64) *StandardRenderingPipeline {
	s.p.Set("motionBlurSamples", motionBlurSamples)
	return s
}

// MotionStrength returns the MotionStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionstrength
func (s *StandardRenderingPipeline) MotionStrength() float64 {
	retVal := s.p.Get("motionStrength")
	return retVal.Float()
}

// SetMotionStrength sets the MotionStrength property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#motionstrength
func (s *StandardRenderingPipeline) SetMotionStrength(motionStrength float64) *StandardRenderingPipeline {
	s.p.Set("motionStrength", motionStrength)
	return s
}

// ObjectBasedMotionBlur returns the ObjectBasedMotionBlur property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#objectbasedmotionblur
func (s *StandardRenderingPipeline) ObjectBasedMotionBlur() bool {
	retVal := s.p.Get("objectBasedMotionBlur")
	return retVal.Bool()
}

// SetObjectBasedMotionBlur sets the ObjectBasedMotionBlur property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#objectbasedmotionblur
func (s *StandardRenderingPipeline) SetObjectBasedMotionBlur(objectBasedMotionBlur bool) *StandardRenderingPipeline {
	s.p.Set("objectBasedMotionBlur", objectBasedMotionBlur)
	return s
}

// OriginalPostProcess returns the OriginalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#originalpostprocess
func (s *StandardRenderingPipeline) OriginalPostProcess() *PostProcess {
	retVal := s.p.Get("originalPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetOriginalPostProcess sets the OriginalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#originalpostprocess
func (s *StandardRenderingPipeline) SetOriginalPostProcess(originalPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("originalPostProcess", originalPostProcess.JSObject())
	return s
}

// Samples returns the Samples property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#samples
func (s *StandardRenderingPipeline) Samples() float64 {
	retVal := s.p.Get("samples")
	return retVal.Float()
}

// SetSamples sets the Samples property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#samples
func (s *StandardRenderingPipeline) SetSamples(samples float64) *StandardRenderingPipeline {
	s.p.Set("samples", samples)
	return s
}

// SourceLight returns the SourceLight property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#sourcelight
func (s *StandardRenderingPipeline) SourceLight() *SpotLight {
	retVal := s.p.Get("sourceLight")
	return SpotLightFromJSObject(retVal, s.ctx)
}

// SetSourceLight sets the SourceLight property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#sourcelight
func (s *StandardRenderingPipeline) SetSourceLight(sourceLight *SpotLight) *StandardRenderingPipeline {
	s.p.Set("sourceLight", sourceLight.JSObject())
	return s
}

// TextureAdderFinalPostProcess returns the TextureAdderFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#textureadderfinalpostprocess
func (s *StandardRenderingPipeline) TextureAdderFinalPostProcess() *PostProcess {
	retVal := s.p.Get("textureAdderFinalPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetTextureAdderFinalPostProcess sets the TextureAdderFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#textureadderfinalpostprocess
func (s *StandardRenderingPipeline) SetTextureAdderFinalPostProcess(textureAdderFinalPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("textureAdderFinalPostProcess", textureAdderFinalPostProcess.JSObject())
	return s
}

// TextureAdderPostProcess returns the TextureAdderPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#textureadderpostprocess
func (s *StandardRenderingPipeline) TextureAdderPostProcess() *PostProcess {
	retVal := s.p.Get("textureAdderPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetTextureAdderPostProcess sets the TextureAdderPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#textureadderpostprocess
func (s *StandardRenderingPipeline) SetTextureAdderPostProcess(textureAdderPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("textureAdderPostProcess", textureAdderPostProcess.JSObject())
	return s
}

// VolumetricLightBlurScale returns the VolumetricLightBlurScale property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightblurscale
func (s *StandardRenderingPipeline) VolumetricLightBlurScale() float64 {
	retVal := s.p.Get("volumetricLightBlurScale")
	return retVal.Float()
}

// SetVolumetricLightBlurScale sets the VolumetricLightBlurScale property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightblurscale
func (s *StandardRenderingPipeline) SetVolumetricLightBlurScale(volumetricLightBlurScale float64) *StandardRenderingPipeline {
	s.p.Set("volumetricLightBlurScale", volumetricLightBlurScale)
	return s
}

// VolumetricLightCoefficient returns the VolumetricLightCoefficient property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightcoefficient
func (s *StandardRenderingPipeline) VolumetricLightCoefficient() float64 {
	retVal := s.p.Get("volumetricLightCoefficient")
	return retVal.Float()
}

// SetVolumetricLightCoefficient sets the VolumetricLightCoefficient property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightcoefficient
func (s *StandardRenderingPipeline) SetVolumetricLightCoefficient(volumetricLightCoefficient float64) *StandardRenderingPipeline {
	s.p.Set("volumetricLightCoefficient", volumetricLightCoefficient)
	return s
}

// VolumetricLightFinalPostProcess returns the VolumetricLightFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightfinalpostprocess
func (s *StandardRenderingPipeline) VolumetricLightFinalPostProcess() *PostProcess {
	retVal := s.p.Get("volumetricLightFinalPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetVolumetricLightFinalPostProcess sets the VolumetricLightFinalPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightfinalpostprocess
func (s *StandardRenderingPipeline) SetVolumetricLightFinalPostProcess(volumetricLightFinalPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("volumetricLightFinalPostProcess", volumetricLightFinalPostProcess.JSObject())
	return s
}

// VolumetricLightMergePostProces returns the VolumetricLightMergePostProces property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightmergepostproces
func (s *StandardRenderingPipeline) VolumetricLightMergePostProces() *PostProcess {
	retVal := s.p.Get("volumetricLightMergePostProces")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetVolumetricLightMergePostProces sets the VolumetricLightMergePostProces property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightmergepostproces
func (s *StandardRenderingPipeline) SetVolumetricLightMergePostProces(volumetricLightMergePostProces *PostProcess) *StandardRenderingPipeline {
	s.p.Set("volumetricLightMergePostProces", volumetricLightMergePostProces.JSObject())
	return s
}

// VolumetricLightPostProcess returns the VolumetricLightPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightpostprocess
func (s *StandardRenderingPipeline) VolumetricLightPostProcess() *PostProcess {
	retVal := s.p.Get("volumetricLightPostProcess")
	return PostProcessFromJSObject(retVal, s.ctx)
}

// SetVolumetricLightPostProcess sets the VolumetricLightPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightpostprocess
func (s *StandardRenderingPipeline) SetVolumetricLightPostProcess(volumetricLightPostProcess *PostProcess) *StandardRenderingPipeline {
	s.p.Set("volumetricLightPostProcess", volumetricLightPostProcess.JSObject())
	return s
}

// VolumetricLightPower returns the VolumetricLightPower property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightpower
func (s *StandardRenderingPipeline) VolumetricLightPower() float64 {
	retVal := s.p.Get("volumetricLightPower")
	return retVal.Float()
}

// SetVolumetricLightPower sets the VolumetricLightPower property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightpower
func (s *StandardRenderingPipeline) SetVolumetricLightPower(volumetricLightPower float64) *StandardRenderingPipeline {
	s.p.Set("volumetricLightPower", volumetricLightPower)
	return s
}

// VolumetricLightSmoothXPostProcess returns the VolumetricLightSmoothXPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightsmoothxpostprocess
func (s *StandardRenderingPipeline) VolumetricLightSmoothXPostProcess() *BlurPostProcess {
	retVal := s.p.Get("volumetricLightSmoothXPostProcess")
	return BlurPostProcessFromJSObject(retVal, s.ctx)
}

// SetVolumetricLightSmoothXPostProcess sets the VolumetricLightSmoothXPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightsmoothxpostprocess
func (s *StandardRenderingPipeline) SetVolumetricLightSmoothXPostProcess(volumetricLightSmoothXPostProcess *BlurPostProcess) *StandardRenderingPipeline {
	s.p.Set("volumetricLightSmoothXPostProcess", volumetricLightSmoothXPostProcess.JSObject())
	return s
}

// VolumetricLightSmoothYPostProcess returns the VolumetricLightSmoothYPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightsmoothypostprocess
func (s *StandardRenderingPipeline) VolumetricLightSmoothYPostProcess() *BlurPostProcess {
	retVal := s.p.Get("volumetricLightSmoothYPostProcess")
	return BlurPostProcessFromJSObject(retVal, s.ctx)
}

// SetVolumetricLightSmoothYPostProcess sets the VolumetricLightSmoothYPostProcess property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightsmoothypostprocess
func (s *StandardRenderingPipeline) SetVolumetricLightSmoothYPostProcess(volumetricLightSmoothYPostProcess *BlurPostProcess) *StandardRenderingPipeline {
	s.p.Set("volumetricLightSmoothYPostProcess", volumetricLightSmoothYPostProcess.JSObject())
	return s
}

// VolumetricLightStepsCount returns the VolumetricLightStepsCount property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightstepscount
func (s *StandardRenderingPipeline) VolumetricLightStepsCount() float64 {
	retVal := s.p.Get("volumetricLightStepsCount")
	return retVal.Float()
}

// SetVolumetricLightStepsCount sets the VolumetricLightStepsCount property of class StandardRenderingPipeline.
//
// https://doc.babylonjs.com/api/classes/babylon.standardrenderingpipeline#volumetriclightstepscount
func (s *StandardRenderingPipeline) SetVolumetricLightStepsCount(volumetricLightStepsCount float64) *StandardRenderingPipeline {
	s.p.Set("volumetricLightStepsCount", volumetricLightStepsCount)
	return s
}
