// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// IAccessorSparseIndices represents a babylon.js IAccessorSparseIndices.
// Indices of those attributes that deviate from their initialization value
type IAccessorSparseIndices struct {
	*IProperty
	ctx js.Value
}

// JSObject returns the underlying js.Value.
func (i *IAccessorSparseIndices) JSObject() js.Value { return i.p }

// IAccessorSparseIndices returns a IAccessorSparseIndices JavaScript class.
func (ba *Babylon) IAccessorSparseIndices() *IAccessorSparseIndices {
	p := ba.ctx.Get("IAccessorSparseIndices")
	return IAccessorSparseIndicesFromJSObject(p, ba.ctx)
}

// IAccessorSparseIndicesFromJSObject returns a wrapped IAccessorSparseIndices JavaScript class.
func IAccessorSparseIndicesFromJSObject(p js.Value, ctx js.Value) *IAccessorSparseIndices {
	return &IAccessorSparseIndices{IProperty: IPropertyFromJSObject(p, ctx), ctx: ctx}
}

// IAccessorSparseIndicesArrayToJSArray returns a JavaScript Array for the wrapped array.
func IAccessorSparseIndicesArrayToJSArray(array []*IAccessorSparseIndices) []interface{} {
	var result []interface{}
	for _, v := range array {
		result = append(result, v.JSObject())
	}
	return result
}

// BufferView returns the BufferView property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#bufferview
func (i *IAccessorSparseIndices) BufferView() float64 {
	retVal := i.p.Get("bufferView")
	return retVal.Float()
}

// SetBufferView sets the BufferView property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#bufferview
func (i *IAccessorSparseIndices) SetBufferView(bufferView float64) *IAccessorSparseIndices {
	i.p.Set("bufferView", bufferView)
	return i
}

// ByteOffset returns the ByteOffset property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#byteoffset
func (i *IAccessorSparseIndices) ByteOffset() float64 {
	retVal := i.p.Get("byteOffset")
	return retVal.Float()
}

// SetByteOffset sets the ByteOffset property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#byteoffset
func (i *IAccessorSparseIndices) SetByteOffset(byteOffset float64) *IAccessorSparseIndices {
	i.p.Set("byteOffset", byteOffset)
	return i
}

// ComponentType returns the ComponentType property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#componenttype
func (i *IAccessorSparseIndices) ComponentType() js.Value {
	retVal := i.p.Get("componentType")
	return retVal
}

// SetComponentType sets the ComponentType property of class IAccessorSparseIndices.
//
// https://doc.babylonjs.com/api/classes/babylon.iaccessorsparseindices#componenttype
func (i *IAccessorSparseIndices) SetComponentType(componentType js.Value) *IAccessorSparseIndices {
	i.p.Set("componentType", componentType)
	return i
}
