// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// NormalMaterial represents a babylon.js NormalMaterial.
//
type NormalMaterial struct{}

// JSObject returns the underlying js.Value.
func (n *NormalMaterial) JSObject() js.Value { return n.p }

// NormalMaterial returns a NormalMaterial JavaScript class.
func (b *Babylon) NormalMaterial() *NormalMaterial {
	p := b.ctx.Get("NormalMaterial")
	return NormalMaterialFromJSObject(p)
}

// NormalMaterialFromJSObject returns a wrapped NormalMaterial JavaScript class.
func NormalMaterialFromJSObject(p js.Value) *NormalMaterial {
	return &NormalMaterial{p: p}
}

// NewNormalMaterial returns a new NormalMaterial object.
//
// https://doc.babylonjs.com/api/classes/babylon.normalmaterial
func (b *Babylon) NewNormalMaterial(todo parameters) *NormalMaterial {
	p := b.ctx.Get("NormalMaterial").New(todo)
	return NormalMaterialFromJSObject(p)
}

// TODO: methods
