// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// DDSTools represents a babylon.js DDSTools.
// Class used to provide DDS decompression tools
type DDSTools struct{}

// JSObject returns the underlying js.Value.
func (d *DDSTools) JSObject() js.Value { return d.p }

// DDSTools returns a DDSTools JavaScript class.
func (b *Babylon) DDSTools() *DDSTools {
	p := b.ctx.Get("DDSTools")
	return DDSToolsFromJSObject(p)
}

// DDSToolsFromJSObject returns a wrapped DDSTools JavaScript class.
func DDSToolsFromJSObject(p js.Value) *DDSTools {
	return &DDSTools{p: p}
}

// NewDDSTools returns a new DDSTools object.
//
// https://doc.babylonjs.com/api/classes/babylon.ddstools
func (b *Babylon) NewDDSTools(todo parameters) *DDSTools {
	p := b.ctx.Get("DDSTools").New(todo)
	return DDSToolsFromJSObject(p)
}

// TODO: methods
