// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// HDRTools represents a babylon.js HDRTools.
// This groups tools to convert HDR texture to native colors array.
type HDRTools struct{}

// JSObject returns the underlying js.Value.
func (h *HDRTools) JSObject() js.Value { return h.p }

// HDRTools returns a HDRTools JavaScript class.
func (b *Babylon) HDRTools() *HDRTools {
	p := b.ctx.Get("HDRTools")
	return HDRToolsFromJSObject(p)
}

// HDRToolsFromJSObject returns a wrapped HDRTools JavaScript class.
func HDRToolsFromJSObject(p js.Value) *HDRTools {
	return &HDRTools{p: p}
}

// NewHDRTools returns a new HDRTools object.
//
// https://doc.babylonjs.com/api/classes/babylon.hdrtools
func (b *Babylon) NewHDRTools(todo parameters) *HDRTools {
	p := b.ctx.Get("HDRTools").New(todo)
	return HDRToolsFromJSObject(p)
}

// TODO: methods
