// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// RefractionTexture represents a babylon.js RefractionTexture.
// Creates a refraction texture used by refraction channel of the standard material.
// It is like a mirror but to see through a material.

//
// See: https://doc.babylonjs.com/how_to/reflect#refraction
type RefractionTexture struct{ *RenderTargetTexture }

// JSObject returns the underlying js.Value.
func (r *RefractionTexture) JSObject() js.Value { return r.p }

// RefractionTexture returns a RefractionTexture JavaScript class.
func (b *Babylon) RefractionTexture() *RefractionTexture {
	p := b.ctx.Get("RefractionTexture")
	return RefractionTextureFromJSObject(p)
}

// RefractionTextureFromJSObject returns a wrapped RefractionTexture JavaScript class.
func RefractionTextureFromJSObject(p js.Value) *RefractionTexture {
	return &RefractionTexture{RenderTargetTextureFromJSObject(p)}
}

// NewRefractionTexture returns a new RefractionTexture object.
//
// https://doc.babylonjs.com/api/classes/babylon.refractiontexture
func (b *Babylon) NewRefractionTexture(todo parameters) *RefractionTexture {
	p := b.ctx.Get("RefractionTexture").New(todo)
	return RefractionTextureFromJSObject(p)
}

// TODO: methods
