// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// PassCubePostProcess represents a babylon.js PassCubePostProcess.
// PassCubePostProcess which produces an output the same as it&amp;#39;s input (which must be a cube texture)
type PassCubePostProcess struct{ *PostProcess }

// JSObject returns the underlying js.Value.
func (p *PassCubePostProcess) JSObject() js.Value { return p.p }

// PassCubePostProcess returns a PassCubePostProcess JavaScript class.
func (b *Babylon) PassCubePostProcess() *PassCubePostProcess {
	p := b.ctx.Get("PassCubePostProcess")
	return PassCubePostProcessFromJSObject(p)
}

// PassCubePostProcessFromJSObject returns a wrapped PassCubePostProcess JavaScript class.
func PassCubePostProcessFromJSObject(p js.Value) *PassCubePostProcess {
	return &PassCubePostProcess{PostProcessFromJSObject(p)}
}

// NewPassCubePostProcessOpts contains optional parameters for NewPassCubePostProcess.
type NewPassCubePostProcessOpts struct {
	Camera *Camera

	SamplingMode *float64

	Engine *Engine

	Reusable *bool

	TextureType *float64

	BlockCompilation *bool
}

// NewPassCubePostProcess returns a new PassCubePostProcess object.
//
// https://doc.babylonjs.com/api/classes/babylon.passcubepostprocess
func (b *Babylon) NewPassCubePostProcess(name string, options float64, opts *NewPassCubePostProcessOpts) *PassCubePostProcess {
	if opts == nil {
		opts = &NewPassCubePostProcessOpts{}
	}

	p := b.ctx.Get("PassCubePostProcess").New(name, options, opts.Camera.JSObject(), opts.SamplingMode, opts.Engine.JSObject(), opts.Reusable.JSObject(), opts.TextureType, opts.BlockCompilation.JSObject())
	return PassCubePostProcessFromJSObject(p)
}

// TODO: methods
