// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// FreeCameraMouseInput represents a babylon.js FreeCameraMouseInput.
// Manage the mouse inputs to control the movement of a free camera.

//
// See: http://doc.babylonjs.com/how_to/customizing_camera_inputs
type FreeCameraMouseInput struct{}

// JSObject returns the underlying js.Value.
func (f *FreeCameraMouseInput) JSObject() js.Value { return f.p }

// FreeCameraMouseInput returns a FreeCameraMouseInput JavaScript class.
func (b *Babylon) FreeCameraMouseInput() *FreeCameraMouseInput {
	p := b.ctx.Get("FreeCameraMouseInput")
	return FreeCameraMouseInputFromJSObject(p)
}

// FreeCameraMouseInputFromJSObject returns a wrapped FreeCameraMouseInput JavaScript class.
func FreeCameraMouseInputFromJSObject(p js.Value) *FreeCameraMouseInput {
	return &FreeCameraMouseInput{p: p}
}

// NewFreeCameraMouseInput returns a new FreeCameraMouseInput object.
//
// https://doc.babylonjs.com/api/classes/babylon.freecameramouseinput
func (b *Babylon) NewFreeCameraMouseInput(todo parameters) *FreeCameraMouseInput {
	p := b.ctx.Get("FreeCameraMouseInput").New(todo)
	return FreeCameraMouseInputFromJSObject(p)
}

// TODO: methods
