// Code generated by docs2go. DO NOT EDIT.

package babylon

import (
	"syscall/js"
)

// IShaderMaterialOptions represents a babylon.js IShaderMaterialOptions.
// Defines the options associated with the creation of a shader material.
type IShaderMaterialOptions struct {
	p   js.Value
	ctx js.Value
}

// JSObject returns the underlying js.Value.
func (i *IShaderMaterialOptions) JSObject() js.Value { return i.p }

// IShaderMaterialOptions returns a IShaderMaterialOptions JavaScript class.
func (ba *Babylon) IShaderMaterialOptions() *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions")
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// IShaderMaterialOptionsFromJSObject returns a wrapped IShaderMaterialOptions JavaScript class.
func IShaderMaterialOptionsFromJSObject(p js.Value, ctx js.Value) *IShaderMaterialOptions {
	return &IShaderMaterialOptions{p: p, ctx: ctx}
}

// IShaderMaterialOptionsArrayToJSArray returns a JavaScript Array for the wrapped array.
func IShaderMaterialOptionsArrayToJSArray(array []*IShaderMaterialOptions) []interface{} {
	var result []interface{}
	for _, v := range array {
		result = append(result, v.JSObject())
	}
	return result
}

/*

// Attributes returns the Attributes property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#attributes
func (i *IShaderMaterialOptions) Attributes(attributes string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(attributes)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetAttributes sets the Attributes property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#attributes
func (i *IShaderMaterialOptions) SetAttributes(attributes string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(attributes)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// Defines returns the Defines property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#defines
func (i *IShaderMaterialOptions) Defines(defines string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(defines)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetDefines sets the Defines property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#defines
func (i *IShaderMaterialOptions) SetDefines(defines string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(defines)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// NeedAlphaBlending returns the NeedAlphaBlending property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#needalphablending
func (i *IShaderMaterialOptions) NeedAlphaBlending(needAlphaBlending bool) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(needAlphaBlending)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetNeedAlphaBlending sets the NeedAlphaBlending property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#needalphablending
func (i *IShaderMaterialOptions) SetNeedAlphaBlending(needAlphaBlending bool) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(needAlphaBlending)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// NeedAlphaTesting returns the NeedAlphaTesting property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#needalphatesting
func (i *IShaderMaterialOptions) NeedAlphaTesting(needAlphaTesting bool) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(needAlphaTesting)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetNeedAlphaTesting sets the NeedAlphaTesting property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#needalphatesting
func (i *IShaderMaterialOptions) SetNeedAlphaTesting(needAlphaTesting bool) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(needAlphaTesting)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// Samplers returns the Samplers property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#samplers
func (i *IShaderMaterialOptions) Samplers(samplers string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(samplers)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetSamplers sets the Samplers property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#samplers
func (i *IShaderMaterialOptions) SetSamplers(samplers string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(samplers)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// UniformBuffers returns the UniformBuffers property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#uniformbuffers
func (i *IShaderMaterialOptions) UniformBuffers(uniformBuffers string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(uniformBuffers)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetUniformBuffers sets the UniformBuffers property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#uniformbuffers
func (i *IShaderMaterialOptions) SetUniformBuffers(uniformBuffers string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(uniformBuffers)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// Uniforms returns the Uniforms property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#uniforms
func (i *IShaderMaterialOptions) Uniforms(uniforms string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(uniforms)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

// SetUniforms sets the Uniforms property of class IShaderMaterialOptions.
//
// https://doc.babylonjs.com/api/classes/babylon.ishadermaterialoptions#uniforms
func (i *IShaderMaterialOptions) SetUniforms(uniforms string) *IShaderMaterialOptions {
	p := ba.ctx.Get("IShaderMaterialOptions").New(uniforms)
	return IShaderMaterialOptionsFromJSObject(p, ba.ctx)
}

*/
